# Dependabot configuration for automated dependency updates
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Bun/npm dependencies (primary package manager)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
      timezone: "UTC"
    # Group development dependencies together
    groups:
      development-dependencies:
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "prettier*"
          - "husky*"
          - "lint-staged*"
          - "c8*"
        update-types:
          - "minor"
          - "patch"
      # Group TypeScript and related tools
      typescript-ecosystem:
        patterns:
          - "typescript"
          - "pyright"
        update-types:
          - "minor"
          - "patch"
    # Configure PR settings
    open-pull-requests-limit: 5
    reviewers:
      - "teamchong"
    # Add semantic commit messages
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    # Only auto-merge patch updates for dev dependencies
    allow:
      - dependency-type: "development"
        update-type: "version-update:semver-patch"
    # Ignore major updates for critical dependencies (require manual review)
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/bun"
        update-types: ["version-update:semver-major"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "1"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    reviewers:
      - "teamchong"
    commit-message:
      prefix: "chore(ci)"
    # Group all GitHub Actions updates together
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"