version: '3.8'

services:
  claude-lsp:
    build: .
    container_name: claude-code-lsp
    ports:
      - "3939:3939"
    volumes:
      # Mount your project directory
      - ${CLAUDE_LSP_PROJECT_DIR:-./}:/workspace:ro
    environment:
      - CLAUDE_LSP_PROJECT_ROOT=/workspace
      - CLAUDE_LSP_PORT=3939
      - CLAUDE_LSP_DEBUG=${CLAUDE_LSP_DEBUG:-false}
      - CLAUDE_LSP_AUTO_INSTALL=true
    restart: unless-stopped
    networks:
      - lsp-network

networks:
  lsp-network:
    driver: bridge