name: CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Install system packages for testing
        run: |
          # Install Scala (needed for Scala tests)
          sudo apt-get update
          sudo apt-get install -y scala
          
          # Show installed tools
          echo "Checking available tools:"
          which tsc && tsc --version || echo "TypeScript not found globally"
          which pyright && pyright --version || echo "Pyright not found globally"
          which scalac && scalac -version || echo "Scala not found"
          
          # Check local tools
          test -f node_modules/.bin/tsc && echo "✅ TypeScript found locally" || echo "❌ TypeScript not found locally"
          test -f node_modules/.bin/pyright && echo "✅ Pyright found locally" || echo "❌ Pyright not found locally"
      
      - name: Build binaries
        run: bun run build
      
      - name: Run tests
        run: bun test
      
      - name: Test CLI source
        run: bun run src/cli.ts --help
      
      - name: Test CLI binary
        run: ./bin/claude-lsp-cli --help
      
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: bin/