name: Test Suite

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Install language tools for testing
      run: |
        # Install TypeScript
        npm install -g typescript
        
        # Install Python type checker
        npm install -g pyright
        
        # Install Scala (needed for Scala tests)
        sudo apt-get update
        sudo apt-get install -y scala
        
        # Show installed tools
        echo "Installed language tools:"
        which tsc && tsc --version || echo "TypeScript not found"
        which pyright && pyright --version || echo "Pyright not found"
        which scalac && scalac -version || echo "Scala not found"
    
    - name: Run tests
      run: bun test --timeout 30000
      
    - name: Check test coverage
      run: |
        echo "Test files: $(ls tests/*.test.ts | wc -l)"
        echo "Source files: $(ls src/*.ts | wc -l)"
        echo "Coverage: $(($(ls tests/*.test.ts | wc -l) * 100 / $(ls src/*.ts | wc -l)))%"
    
    - name: Build binaries
      run: bun run build
      
    - name: Verify binary exists
      run: |
        test -f bin/claude-lsp-cli
        echo "✅ Single unified binary built successfully"